
function createProduct() {
    if (localStorage.getItem('products') === null) {
        let products = [
            {
                id: 1,
                name: "Ốp Lưng Naruto",
                img: "./img/product/Case/sumsung_anime (14).png",
                category: "Anime",
                brand: "Apple",
                model: "Samsung Galaxy A51",
                price: 200000,
                quantity: 40,
                sold: 0,
                totalRevenue: 0,
                desc: "Ốp lưng hình Naruto phong cách mạnh mẽ."
            },
            {
                id: 2,
                name: "Ốp Lưng One Piece",
                img: "./img/product/Case/iphone_anime (6).png",
                category: "Anime",
                brand: "Apple",
                model: "IPhone 14 Pro/Iphone 14 Pro Max",
                price: 190000,
                quantity: 30,
                sold: 0,
                totalRevenue: 0,
                desc: "Thiết kế hình Luffy, dành cho fan One Piece."
            },
            {
                id: 3,
                name: "Ốp Lưng Vegeta",
                img: "./img/product/Case/iphone_anime (8).png",
                category: "Anime",
                brand: "Apple",
                model: "IPhone 13 Mini/IPhone 13",
                price: 180000,
                quantity: 45,
                sold: 0,
                totalRevenue: 0,
                desc: "Ốp lưng Vegeta biến hóa đa dạng."
            },
            {
                id: 4,
                name: "Ốp Lưng Demon Slayer",
                img: "./img/product/Case/iphone_anime (2).png",
                category: "Anime",
                brand: "Apple",
                model: "IPhone 15 Pro/IPhone 15 Pro Max",
                price: 210000,
                quantity: 35,
                sold: 0,
                totalRevenue: 0,
                desc: "Ốp lưng hình trang phục Tanjiro dễ thương."
            },
            {
                id: 5,
                name: "Ốp Lưng Dragon Ball",
                img: "./img/product/Case/iphone_anime (10).png",
                category: "Anime",
                brand: "Apple",
                model: "IPhone 12/IPhone 12 Pro",
                price: 170000,
                quantity: 50,
                sold: 0,
                totalRevenue: 0,
                desc: "Hình ảnh Goku cưỡi cân đẩu vân đầy năng lượng."
            },
            {
                id: 6,
                name: "Ốp Lưng Wanted One Piece",
                img: "./img/product/Case/iphone_anime (15).png",
                category: "Anime",
                brand: "Apple",
                model: "IPhone 11/IPhone 11 Pro",
                price: 185000,
                quantity: 25,
                sold: 0,
                totalRevenue: 0,
                desc: "Hình ảnh truy nã của toàn bộ băng mũ rơm."
            },
            {
                id: 7,
                name: "Ốp Lưng Uchiha",
                img: "./img/product/Case/iphone_anime (14).png",
                category: "Anime",
                brand: "Apple",
                model: "IPhone XR/IPhone XS",
                price: 195000,
                quantity: 38,
                sold: 0,
                totalRevenue: 0,
                desc: "Hình ảnh Itachi siêu ngầu, truyền cảm hứng."
            },
            {
                id: 8,
                name: "Ốp Lưng Tokyo Revengers",
                img: "./img/product/Case/iphone_anime (11).png",
                category: "Anime",
                brand: "Apple",
                model: "IPhone 13 Pro/IPhone 13 Pro Max",
                price: 220000,
                quantity: 20,
                sold: 0,
                totalRevenue: 0,
                desc: "Ốp lưng Mikey mạnh mẽ và đầy phong cách."
            },
            {
                id: 9,
                name: "Ốp Lưng Messi",
                img: "./img/product/Case/samsung_sport (15).png",
                category: "Sport",
                brand: "Apple",
                model: "Samsung Galaxy S24 Ultra",
                price: 160000,
                quantity: 60,
                sold: 0,
                totalRevenue: 0,
                desc: "Tên của Messi được thiết kế đầy phong cách."
            },
            {
                id: 10,
                name: "Ốp Lưng Ronaldo",
                img: "./img/product/Case/samsung_sport (12).png",
                category: "Sport",
                brand: "Apple",
                model: "Samsung Galaxy S22",
                price: 180000,
                quantity: 50,
                sold: 0,
                totalRevenue: 0,
                desc: "Hình ảnh Pose dáng ăn mừng của Ronaldo."
            },
            {
                id: 11,
                name: "Ốp Lưng James",
                img: "./img/product/Case/samsung_sport (13).png",
                category: "Sport",
                brand: "Apple",
                model: "Samsung Galaxy S22 Plus",
                price: 170000,
                quantity: 45,
                sold: 0,
                totalRevenue: 0,
                desc: "Thiết kế King James."
            },
            {
                id: 12,
                name: "Ốp Lưng Barcelona",
                img: "./img/product/Case/samsung_sport (10).png",
                category: "Sport",
                brand: "Apple",
                model: "Samsung Galaxy S22",
                price: 190000,
                quantity: 40,
                sold: 0,
                totalRevenue: 0,
                desc: "Hình ảnh màu áo Barcelona."
            },
            {
                id: 13,
                name: "Ốp Lưng Hàn Quốc",
                img: "./img/product/Case/iphone_sport (6).png",
                category: "Sport",
                brand: "Apple",
                model: "IPhone 14",
                price: 200000,
                quantity: 35,
                sold: 0,
                totalRevenue: 0,
                desc: "Hình ảnh màu áo của quê hương Ronaldo, người hùng Hàn Quốc."
            },
            {
                id: 14,
                name: "Ốp Lưng Neymar JR",
                img: "./img/product/Case/iphone_sport (12).png",
                category: "Sport",
                brand: "Apple",
                model: "IPhone 14 Plus",
                price: 175000,
                quantity: 30,
                sold: 0,
                totalRevenue: 0,
                desc: "Ốp lưng hình áo Neymar JR."
            },
            {
                id: 15,
                name: "Ốp Lưng Ronaldo MU",
                img: "./img/product/Case/iphone_sport (8).png",
                category: "Sport",
                brand: "Apple",
                model: "IPhone 11 Pro",
                price: 185000,
                quantity: 28,
                sold: 0,
                totalRevenue: 0,
                desc: "Hình ảnh áo Manchester United của Ronaldo."
            },
            {
                id: 16,
                name: "Ốp Lưng Argentina",
                img: "./img/product/Case/iphone_sport (17).png",
                category: "Sport",
                brand: "Apple",
                model: "IPhone 15 Pro Max",
                price: 210000,
                quantity: 20,
                sold: 0,
                totalRevenue: 0,
                desc: "Hình ảnh áo Argentina của Messi."
            },
            {
                id: 17,
                name: "Ốp Lưng hoa văn",
                img: "./img/product/Case/iphone_artwork (1).png",
                category: "Art",
                brand: "Apple",
                model: "IPhone 16 Pro",
                price: 230000,
                quantity: 28,
                sold: 0,
                totalRevenue: 0,
                desc: "Ốp lưng họa tiết bắt mắt."
            },
            {
                id: 18,
                name: "Ốp Lưng tranh Van Gogh",
                img: "./img/product/Case/iphone_artwork (2).png",
                category: "Art",
                brand: "Apple",
                model: "IPhone 15 Plus",
                price: 240000,
                quantity: 35,
                sold: 0,
                totalRevenue: 0,
                desc: "Hình ảnh 'Đêm đầy sao' của Van Gogh."
            },
            {
                id: 19,
                name: "Ốp Lưng phong cảnh",
                img: "./img/product/Case/iphone_artwork (3).png",
                category: "Art",
                brand: "Apple",
                model: "IPhone 14",
                price: 220000,
                quantity: 32,
                sold: 0,
                totalRevenue: 0,
                desc: "Ốp lưng với cảnh sắc thiên nhiên thanh bình."
            },
            {
                id: 20,
                name: "Ốp Lưng tranh sơn dầu",
                img: "./img/product/Case/iphone_artwork (9).png",
                category: "Art",
                brand: "Apple",
                model: "IPhone 13 Mini",
                price: 210000,
                quantity: 40,
                sold: 0,
                totalRevenue: 0,
                desc: "Hình ảnh sơn dầu đậm chất nghệ thuật, lấy cảm hứng từ bức tranh Đêm đầy sao của Van Gogh."
            },
            {
                id: 21,
                name: "Ốp Lưng tranh trừu tượng",
                img: "./img/product/Case/iphone_artwork (5).png",
                category: "Art",
                brand: "Apple",
                model: "IPhone 12 Pro",
                price: 250000,
                quantity: 25,
                sold: 0,
                totalRevenue: 0,
                desc: "Tác phẩm nghệ thuật trừu tượng ấn tượng."
            },
            {
                id: 22,
                name: "Ốp Lưng hoa anh đào",
                img: "./img/product/Case/iphone_artwork (6).png",
                category: "Art",
                brand: "Apple",
                model: "IPhone SE 2022",
                price: 200000,
                quantity: 30,
                sold: 0,
                totalRevenue: 0,
                desc: "Hình ảnh hoa anh đào tinh tế."
            },
            {
                id: 23,
                name: "Ốp Lưng phong cách cổ điển",
                img: "./img/product/Case/iphone_artwork (7).png",
                category: "Art",
                brand: "Apple",
                model: "IPhone XR",
                price: 100000,
                quantity: 29,
                sold: 0,
                totalRevenue: 0,
                desc: "Họa tiết cổ điển, sang trọng."
            },
            {
                id: 24,
                name: "Ốp Lưng tranh mùa thu",
                img: "./img/product/Case/iphone_artwork (8).png",
                category: "Art",
                brand: "Apple",
                model: "IPhone 11",
                price: 215000,
                quantity: 38,
                sold: 0,
                totalRevenue: 0,
                desc: "Phong cảnh mùa thu nhẹ nhàng, lãng mạn."
            },
            {
                id: 25,
                name: "Ốp lưng Vịt vàng",
                img: "./img/product/Case/samsung_game (1).png",
                category: "Game",
                brand: "Apple",
                model: "Samsung Galaxy S24 Ultra",
                price: 250000,
                quantity: 30,
                sold: 0,
                totalRevenue: 0,
                desc: "Vịt vàng hóa thiên nga, dành cho người hâm mộ tựa game",
            },
            {
                id: 26,
                name: "Ốp lưng Sponbob funny",
                img: "./img/product/Case/samsung_game (2).png",
                category: "Game",
                brand: "Apple",
                model: "Samsung Galaxy S22 Ultra",
                price: 350000,
                quantity: 50,
                sold: 0,
                totalRevenue: 0,
                desc: "Trò chơi vui nhộn",
            },
            {
                id: 27,
                name: "Ốp lưng Ball Game",
                img: "./img/product/Case/samsung_game (3).png",
                category: "Game",
                brand: "Apple",
                model: "Samsung Galaxy S23",
                price: 400000,
                quantity: 20,
                sold: 0,
                totalRevenue: 0,
                desc: "Pick a ball and shoot",
            },
            {
                id: 28,
                name: "Ốp lưng Cừu hồng Minecraft",
                img: "./img/product/Case/samsung_game (4).png",
                category: "Game",
                brand: "Apple",
                model: "Samsung Galaxy S24 Ultra",
                price: 250000,
                quantity: 30,
                sold: 0,
                totalRevenue: 0,
                desc: "Cừu Hồng minecraft cực hiếm và sặc sỡ sắc màu",
            },
            {
                id: 29,
                name: "Ốp lưng Mario Jump",
                img: "./img/product/Case/samsung_game (5).png",
                category: "Game",
                brand: "Apple",
                model: "Samsung Galaxy S21",
                price: 280000,
                quantity: 25,
                sold: 0,
                totalRevenue: 0,
                desc: "Thiết kế Mario đang nhảy qua chướng ngại vật."
            },
            {
                id: 30,
                name: "Ốp lưng Pikachu Power",
                img: "./img/product/Case/samsung_game (6).png",
                category: "Game",
                brand: "Apple",
                model: "Samsung Galaxy S23 Plus",
                price: 320000,
                quantity: 40,
                sold: 0,
                totalRevenue: 0,
                desc: "Pikachu đầy năng lượng dành cho fan Pokémon."
            },
            {
                id: 31,
                name: "Ốp lưng Máy chơi game",
                img: "./img/product/Case/samsung_game (7).png",
                category: "Game",
                brand: "Apple",
                model: "Samsung Galaxy S20 FE",
                price: 300000,
                quantity: 35,
                sold: 0,
                totalRevenue: 0,
                desc: "Phiên bản máy chơi game đủ thể loại."
            },
            {
                id: 32,
                name: "Ốp lưng T1",
                img: "./img/product/Case/iphone_game (2).png",
                category: "Game",
                brand: "Apple",
                model: "IPhone 14",
                price: 450000,
                quantity: 30,
                sold: 0,
                totalRevenue: 0,
                desc: "Logo đội tuyển tựa game Liên Minh Huyền Thoại - vua về nhì T1."
            },
            {
                id: 34,
                name: "Ốp lưng chú mèo Pusheen",
                img: "./img/product/Case/iphone_cartoon (2).png",
                category: "Cartoon",
                brand: "Apple",
                model: "Iphone 15 Pro",
                price: 270000,
                quantity: 25,
                sold: 0,
                totalRevenue: 0,
                desc: "Hình ảnh Pusheen đáng yêu dành cho người yêu mèo."
            },
            {
                "id": 35,
                "name": "Ốp lưng Minion vui nhộn",
                "img": "./img/product/Case/iphone_cartoon (3).png",
                category: "Cartoon",
                brand: "Apple",
                model: "Iphone 14 Plus",
                price: 290000,
                quantity: 35,
                sold: 0,
                totalRevenue: 0,
                desc: "Minion tinh nghịch khiến ai cũng thích thú."
            },
            {
                "id": 36,
                "name": "Ốp lưng Scooby-Doo thám hiểm",
                "img": "./img/product/Case/iphone_cartoon (4).png",
                category: "Cartoon",
                brand: "Apple",
                model: "Iphone 13 Mini",
                price: 260000,
                quantity: 28,
                sold: 0,
                totalRevenue: 0,
                desc: "Scooby-Doo và những chuyến phiêu lưu hấp dẫn."
            },
            {
                "id": 37,
                "name": "Ốp lưng Captain America",
                "img": "./img/product/Case/iphone_cartoon (5).png",
                category: "Cartoon",
                brand: "Apple",
                model: "Iphone 16 Pro",
                price: 300000,
                quantity: 40,
                sold: 0,
                totalRevenue: 0,
                desc: "Khiên captain America."
            },
            {
                "id": 38,
                "name": "Ốp lưng NewJeans",
                "img": "./img/product/Case/samsung_cartoon (15).png",
                category: "Cartoon",
                brand: "Apple",
                model: "Samsung Galaxy A51",
                price: 150000,
                quantity: 33,
                sold: 0,
                totalRevenue: 0,
                desc: "Hình chú thỏ hoạt hình dễ thương như nhóm nhạc NewJeans."
            },
            {
                "id": 39,
                "name": "Ốp lưng Ghost Rider",
                "img": "./img/product/Case/iphone_cartoon (7).png",
                category: "Cartoon",
                brand: "Apple",
                model: "Iphone 12 Pro",
                price: 310000,
                quantity: 22,
                sold: 0,
                totalRevenue: 0,
                desc: "Thần chết tốc độ siêu cháy."
            },
            {
                "id": 40,
                "name": "Ốp lưng Vịt Donald",
                "img": "./img/product/Case/samsung_cartoon (9).png",
                category: "Cartoon",
                brand: "Apple",
                model: "Samsung 22",
                price: 310000,
                quantity: 22,
                sold: 0,
                totalRevenue: 0,
                desc: "Vịt Donald dễ thương."
            },
            {
                "id": 41,
                "name": "Ốp lưng donut",
                "img": "./img/product/Case/samsung_cartoon (7).png",
                category: "Cartoon",
                brand: "Apple",
                model: "Samsung 22",
                price: 500000,
                quantity: 22,
                sold: 0,
                totalRevenue: 0,
                desc: "Donut all time."
            },

        ];

        localStorage.setItem('products', JSON.stringify(products));
    }
}

window.onload = createProduct();
